version: '3.8'

services:
  casa-costanera:
    build: .
    container_name: casa-costanera-app
    restart: unless-stopped
    ports:
      - "4000:4000"  # Cambiar a otro puerto si 4000 está ocupado
    volumes:
      # Montar carpetas que necesitan persistencia
      - ./database:/app/database
      - ./public/audio:/app/public/audio
      - ./public/playground/logs:/app/public/playground/logs
      - ./src/api/temp:/app/src/api/temp
      - ./.env:/app/.env:ro  # Solo lectura para seguridad
    environment:
      - NODE_ENV=production
      - TZ=America/Santiago
    networks:
      - casa-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # Limitar recursos para no afectar AzuraCast
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

networks:
  casa-network:
    driver: bridge

# Volúmenes nombrados para datos persistentes (opcional)
volumes:
  casa-database:
    driver: local
  casa-audio:
    driver: local