#!/bin/bash

echo "========================================"
echo "PROBADOR DE CONFIGURACIONES DE DUCKING"
echo "========================================"
echo ""
echo "Tienes 3 opciones para probar:"
echo ""
echo "1) DUCKING-FIXED.liq    - Versión con fade suave corregida"
echo "2) DUCKING-SIMPLE.liq   - Versión simple sin threads"
echo "3) DUCKING-MINIMAL.liq  - Versión ultra básica (más estable)"
echo ""
echo "INSTRUCCIONES:"
echo "1. Copia el contenido del archivo que quieras probar"
echo "2. Pégalo en AzuraCast -> Liquidsoap Config"
echo "3. Guarda y reinicia la estación"
echo "4. Ejecuta el test con: php /var/www/casa/src/api/ducking-service.php"
echo ""
echo "Archivos disponibles:"
ls -la /var/www/casa/DUCKING-*.liq
echo ""
echo "RECOMENDACIÓN:"
echo "Empieza con DUCKING-MINIMAL.liq para verificar que funciona"
echo "Luego prueba DUCKING-SIMPLE.liq para ducking sin fade"
echo "Finalmente DUCKING-FIXED.liq para fade suave de 4 segundos"
